"""
Rule definitions catalog for the document screening system.
Every rule specifies:
- rule_id
- document_type
- name
- category
- severity (CRITICAL, MAJOR, MINOR, INFO)
- description
- version
"""

DEFAULT_RULES = [
    {
        "rule_id": "REQ-001",
        "document_type": "PASSPORT",
        "name": "Required Fields Completeness",
        "category": "COMPLETENESS",
        "severity": "CRITICAL",
        "description": "Ensures all mandatory passport fields (Name, Passport Number, Nationality, DOB, Expiry Date) are extracted.",
        "version": "1.0",
    },
    {
        "rule_id": "REQ-002",
        "document_type": "VISA",
        "name": "Required Visa Fields Completeness",
        "category": "COMPLETENESS",
        "severity": "CRITICAL",
        "description": "Ensures mandatory visa fields (Visa Number, Visa Type, Valid From, Valid Until) are present.",
        "version": "1.0",
    },
    {
        "rule_id": "DATE-001",
        "document_type": "ALL",
        "name": "Date Format Validation",
        "category": "FORMAT",
        "severity": "MAJOR",
        "description": "Validates that all dates conform to valid ISO 8601 YYYY-MM-DD representations.",
        "version": "1.0",
    },
    {
        "rule_id": "DATE-002",
        "document_type": "ALL",
        "name": "Document Expiry Validity",
        "category": "VALIDITY",
        "severity": "CRITICAL",
        "description": "Checks that the document expiry date is in the future and not expired.",
        "version": "1.0",
    },
    {
        "rule_id": "DATE-003",
        "document_type": "ALL",
        "name": "Issue vs Expiry Chronology",
        "category": "CONSISTENCY",
        "severity": "CRITICAL",
        "description": "Verifies that expiry date is strictly chronologically after the issue date, within legal maximum term.",
        "version": "1.0",
    },
    {
        "rule_id": "DATE-004",
        "document_type": "ALL",
        "name": "Date of Birth Plausibility",
        "category": "CONSISTENCY",
        "severity": "MAJOR",
        "description": "Verifies that date of birth is in the past and applicant age is realistic (0 to 120 years).",
        "version": "1.0",
    },
    {
        "rule_id": "DATE-005",
        "document_type": "VISA",
        "name": "Visa Stay Duration Consistency",
        "category": "CONSISTENCY",
        "severity": "MAJOR",
        "description": "Ensures permitted stay duration does not exceed the date span between Valid-From and Valid-Until.",
        "version": "1.0",
    },
    {
        "rule_id": "MRZ-001",
        "document_type": "PASSPORT",
        "name": "MRZ Syntax & Presence",
        "category": "MRZ",
        "severity": "CRITICAL",
        "description": "Verifies that Machine Readable Zone is detected and complies with ICAO Doc 9303 TD3 structure.",
        "version": "1.0",
    },
    {
        "rule_id": "MRZ-002",
        "document_type": "PASSPORT",
        "name": "MRZ Document Number Checksum",
        "category": "MRZ",
        "severity": "CRITICAL",
        "description": "Validates ICAO 9303 check digit calculation for passport document number.",
        "version": "1.0",
    },
    {
        "rule_id": "MRZ-003",
        "document_type": "PASSPORT",
        "name": "MRZ Date of Birth Checksum",
        "category": "MRZ",
        "severity": "CRITICAL",
        "description": "Validates ICAO 9303 check digit calculation for date of birth.",
        "version": "1.0",
    },
    {
        "rule_id": "MRZ-004",
        "document_type": "PASSPORT",
        "name": "MRZ Expiry Date Checksum",
        "category": "MRZ",
        "severity": "CRITICAL",
        "description": "Validates ICAO 9303 check digit calculation for document expiry date.",
        "version": "1.0",
    },
    {
        "rule_id": "MRZ-005",
        "document_type": "PASSPORT",
        "name": "MRZ Composite Checksum",
        "category": "MRZ",
        "severity": "CRITICAL",
        "description": "Validates overall ICAO 9303 composite checksum calculated over line 2 data.",
        "version": "1.0",
    },
    {
        "rule_id": "CROSS-001",
        "document_type": "PASSPORT",
        "name": "VIZ to MRZ Document Number Match",
        "category": "CROSS_FIELD",
        "severity": "CRITICAL",
        "description": "Ensures passport number displayed on visual inspection zone (VIZ) matches the MRZ line.",
        "version": "1.0",
    },
    {
        "rule_id": "CROSS-002",
        "document_type": "PASSPORT",
        "name": "VIZ to MRZ Date of Birth Match",
        "category": "CROSS_FIELD",
        "severity": "MAJOR",
        "description": "Ensures visual date of birth matches the encoded MRZ date of birth.",
        "version": "1.0",
    },
    {
        "rule_id": "CROSS-003",
        "document_type": "PASSPORT",
        "name": "VIZ to MRZ Expiry Date Match",
        "category": "CROSS_FIELD",
        "severity": "CRITICAL",
        "description": "Detects discrepancies between visual expiry date and MRZ expiry date (common in fraudulent alterations).",
        "version": "1.0",
    },
    {
        "rule_id": "CROSS-004",
        "document_type": "PASSPORT",
        "name": "VIZ to MRZ Nationality Match",
        "category": "CROSS_FIELD",
        "severity": "MAJOR",
        "description": "Ensures visual nationality matches issuing country / 3-letter code in MRZ.",
        "version": "1.0",
    },
    {
        "rule_id": "CROSS-005",
        "document_type": "PASSPORT",
        "name": "VIZ to MRZ Name Consistency",
        "category": "CROSS_FIELD",
        "severity": "MAJOR",
        "description": "Compares visual full name against surname and given names encoded in MRZ line 1.",
        "version": "1.0",
    },
    {
        "rule_id": "DOC-001",
        "document_type": "ALL",
        "name": "Document Number Pattern Format",
        "category": "FORMAT",
        "severity": "MAJOR",
        "description": "Checks that the document number adheres to standard alphanumeric format constraints.",
        "version": "1.0",
    },
    {
        "rule_id": "REF-001",
        "document_type": "ALL",
        "name": "Authorized Reference System Lookup",
        "category": "REFERENCE",
        "severity": "CRITICAL",
        "description": "Queries authorized border/checkpoint registry to verify document validity and check against watchlists.",
        "version": "1.0",
    },
]
